language: node_js
sudo: false
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
script:
  - istanbul cover mocha -- -R spec
  - ls -al coverage
  - cat coverage/lcov.info
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -d
  de_js:
  - "4"
  - "node"
