language: node_js
sudo: false
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
script:
  - istanbul cover mocha -- -R spec
  - ls -al
  - codecov
node_js:
  - "4"
  - "node"
